modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="prova"
version="1.0.0"
displayName="prova"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="peron, MCreator"

[[dependencies.prova]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




